Dtype: np.int32
Goal: 0.0
Mask1:
  Points:
  - - 3
    - 3
  - - 1
    - 613
  - - 702
    - 3
  - - 6
    - 3
  - - 6
    - 3
Mask2:
  Points:
  - - 1
    - 620
  - - 2
    - 719
  - - 242
    - 718
  - - 1025
    - 2
  - - 705
    - 3
Mask3:
  Points:
  - - 305
    - 716
  - - 581
    - 717
  - - 1278
    - 79
  - - 1277
    - 2
  - - 1043
    - 2
Mask4:
  Points:
  - - 641
    - 715
  - - 1278
    - 718
  - - 1278
    - 122
  - - 1278
    - 122
  - - 1278
    - 122
NumOfMasks: 4
