Dtype: np.int32
Goal: 0.0
Mask1:
  Points:
  - - 0
    - 1
  - - 0
    - 597
  - - 696
    - 2
  - - 1
    - 1
  - - 1
    - 1
Mask2:
  Points:
  - - 1
    - 593
  - - 0
    - 719
  - - 234
    - 719
  - - 956
    - 1
  - - 702
    - 2
Mask3:
  Points:
  - - 248
    - 719
  - - 527
    - 718
  - - 1279
    - 1
  - - 964
    - 0
  - - 965
    - 0
Mask4:
  Points:
  - - 569
    - 719
  - - 819
    - 719
  - - 1279
    - 204
  - - 1279
    - 21
  - - 1279
    - 21
NumOfMasks: 4
