Dtype: np.int32
Goal: 0.0
Mask1:
  Points:
  - - 3
    - 2
  - - 1
    - 421
  - - 458
    - 4
  - - 2
    - 3
  - - 2
    - 3
Mask2:
  Points:
  - - 1
    - 420
  - - 2
    - 478
  - - 169
    - 479
  - - 672
    - 3
  - - 471
    - 3
Mask3:
  Points:
  - - 180
    - 479
  - - 379
    - 477
  - - 846
    - 82
  - - 845
    - 3
  - - 693
    - 1
Mask4:
  Points:
  - - 397
    - 478
  - - 843
    - 479
  - - 846
    - 101
  - - 846
    - 101
  - - 846
    - 101
NumOfMasks: 4
