Dtype: np.int32
Goal: 0.0
Mask1:
  Points:
  - - 3
    - 3
  - - 2
    - 556
  - - 676
    - 4
  - - 5
    - 2
  - - 5
    - 2
Mask2:
  Points:
  - - 2
    - 684
  - - 2
    - 719
  - - 189
    - 719
  - - 967
    - 4
  - - 792
    - 3
Mask3:
  Points:
  - - 289
    - 719
  - - 519
    - 719
  - - 1276
    - 85
  - - 1274
    - 11
  - - 1117
    - 4
Mask4:
  Points:
  - - 605
    - 719
  - - 706
    - 719
  - - 1275
    - 251
  - - 1275
    - 199
  - - 1274
    - 198
NumOfMasks: 4
